name: mirukuru
description: an app use TDD Clean Architecture for Flutter

version: 1.5.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.1
  # Local cache
  shared_preferences: ^2.0.15
  # Loading indicator
  flutter_easyloading: ^3.0.3
  flustars_flutter3: ^3.0.0
  group_list_view: ^1.1.1
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  # Read link rss
  webfeed: ^0.7.0
  # CancelableOperation
  async: ^2.8.2
  flutter_secure_storage: ^7.0.1
  easy_localization: ^3.0.0
  #image process
  image: ^3.1.1
  flutter_native_image: ^0.0.6
  flutter_image_compress: ^1.1.0
  url_launcher: ^6.1.2
  # Logging
  logger: ^1.1.0
  # Network dio
  dio: ^4.0.6
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  path_provider: ^2.0.10
  path: ^1.8.1
  decimal: ^2.2.0
  http: ^0.13.4
  flutter_svg: ^1.0.0
  image_picker: ^0.8.5+3
  flutter_contacts: ^1.1.5
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.2
  flutter_local_notifications: ^9.1.4
  firebase_remote_config: ^3.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.3.2
  test: ^1.16.8
  bloc_test: ^9.1.0

  hive_generator: ^1.1.3
  build_runner: ^2.1.11


flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/translations/
  fonts:
    - family: NotoSansJPBold
      fonts:
          - asset: assets/fonts/NotoSansJPBold.otf
    - family: NotoSansJPRegular
      fonts:
          - asset: assets/fonts/NotoSansJPRegular.otf